workflows:
  android-build:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      vars:
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx1536m"
    scripts:
      - name: Install
        script: |
          echo "Starting build"
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email: false
